In [1]:
import numpy as np

In [2]:
np.random.randint(18,size = (3,3))

array([[11,  4,  7],
       [ 9, 12,  9],
       [ 6,  7,  7]], dtype=int32)

In [62]:
arr1 = np.array([1.1,2.2,3.3])

In [65]:
arr1.dtype

dtype('float64')

In [64]:
arr1

array([1.1, 2.2, 3.3])

In [69]:
arr6 = arr1.astype('int64')

In [70]:
arr6

array([1, 2, 3])

In [71]:
arr6[2] = 333

In [72]:
arr6

array([  1,   2, 333])

In [73]:
arr1

array([1.1, 2.2, 3.3])

In [6]:
arr2 = np.array([1,2,3,4,5,6,7,8,9])

In [7]:
arr2.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr3 = np.array([10,20,30,40,50,60,70,80,90,100])

In [9]:
mask = arr3> 50

In [10]:
arr3[mask]

array([ 60,  70,  80,  90, 100])

In [11]:
arr3[arr3>50]

array([ 60,  70,  80,  90, 100])

In [58]:
arr4 = np.array([[[[1,2,3],[4,5,6]],
                 [[7,8,9],[10,11,12]]],[[[11,12,13],[14,15,16]],[[1,2,3],[4,5,6]]]])

In [59]:
arr4

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[11, 12, 13],
         [14, 15, 16]],

        [[ 1,  2,  3],
         [ 4,  5,  6]]]])

In [60]:
arr4.ndim

4